export const COUNTRIES: { code: string; name: string }[] = [
  { code: "TR", name: "Türkiye" },
  { code: "DE", name: "Almanya" },
  { code: "AL", name: "Arnavutluk" },
  { code: "AT", name: "Avusturya" },
  { code: "AZ", name: "Azerbaycan" },
  { code: "BE", name: "Belçika" },
  { code: "BY", name: "Belarus" },
  { code: "BA", name: "Bosna-Hersek" },
  { code: "BG", name: "Bulgaristan" },
  { code: "CZ", name: "Çekya" },
  { code: "DK", name: "Danimarka" },
  { code: "DZ", name: "Cezayir" },
  { code: "ID", name: "Endonezya" },
  { code: "AM", name: "Ermenistan" },
  { code: "EE", name: "Estonya" },
  { code: "MA", name: "Fas" },
  { code: "FI", name: "Finlandiya" },
  { code: "FR", name: "Fransa" },
  { code: "GE", name: "Gürcistan" },
  { code: "HR", name: "Hırvatistan" },
  { code: "NL", name: "Hollanda" },
  { code: "GB", name: "İngiltere" },
  { code: "IQ", name: "Irak" },
  { code: "IR", name: "İran" },
  { code: "IE", name: "İrlanda" },
  { code: "ES", name: "İspanya" },
  { code: "SE", name: "İsveç" },
  { code: "CH", name: "İsviçre" },
  { code: "IT", name: "İtalya" },
  { code: "IS", name: "İzlanda" },
  { code: "JP", name: "Japonya" },
  { code: "ME", name: "Karadağ" },
  { code: "XK", name: "Kosova" },
  { code: "CY", name: "Kıbrıs" },
  { code: "KZ", name: "Kazakistan" },
  { code: "KG", name: "Kırgızistan" },
  { code: "LV", name: "Letonya" },
  { code: "LT", name: "Litvanya" },
  { code: "HU", name: "Macaristan" },
  { code: "MK", name: "Kuzey Makedonya" },
  { code: "EG", name: "Mısır" },
  { code: "NG", name: "Nijerya" },
  { code: "NO", name: "Norveç" },
  { code: "UZ", name: "Özbekistan" },
  { code: "PK", name: "Pakistan" },
  { code: "PL", name: "Polonya" },
  { code: "PT", name: "Portekiz" },
  { code: "RO", name: "Romanya" },
  { code: "RU", name: "Rusya" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Sırbistan" },
  { code: "SK", name: "Slovakya" },
  { code: "SI", name: "Slovenya" },
  { code: "SY", name: "Suriye" },
  { code: "SA", name: "Suudi Arabistan" },
  { code: "TN", name: "Tunus" },
  { code: "TM", name: "Türkmenistan" },
  { code: "UA", name: "Ukrayna" },
  { code: "UY", name: "Uruguay" },
  { code: "US", name: "ABD" },
  { code: "AR", name: "Arjantin" },
  { code: "BR", name: "Brezilya" },
  { code: "GR", name: "Yunanistan" },
];

const byCode = new Map(COUNTRIES.map((country) => [country.code, country.name]));

export function countryName(code: string | null) {
  if (!code) return "—";
  return byCode.get(code) ?? code;
}
